# Generated by Django 5.2.4 on 2025-07-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('cp', models.IntegerField(verbose_name='Chest Pain Type')),
                ('trestbps', models.IntegerField(verbose_name='Resting Blood Pressure')),
                ('chol', models.IntegerField(verbose_name='Cholesterol')),
                ('fbs', models.IntegerField(verbose_name='Fasting Blood Sugar > 120 mg/dl')),
                ('restecg', models.IntegerField(verbose_name='Resting ECG Result')),
                ('thalach', models.IntegerField(verbose_name='Max Heart Rate Achieved')),
                ('exang', models.IntegerField(verbose_name='Exercise Induced Angina')),
                ('oldpeak', models.FloatField(verbose_name='ST Depression')),
                ('slope', models.IntegerField(verbose_name='Slope of ST Segment')),
                ('ca', models.IntegerField(verbose_name='Number of Major Vessels Colored')),
                ('thal', models.IntegerField(verbose_name='Thalassemia Type')),
                ('result', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
